### ISSUE TITLE
FInvalidatableBrushAttribute undefined.

### ISSUE THREAD

**Issue by glenwrhodes** [bakjos/WebCameraFeed#6]
Hi there. Trying to give this a try (4.23), but when I build I'm getting an error in VS in SWebCameraImage.cpp, line 18:

		Image = FInvalidatableBrushAttribute (&Brush);

VS is saying that FInvalidatableBrushAttribute is an undefined identifier.

**Comment by bakjos** [comment]
@glenwrhodes What visual studio version are you using? For me is working with UE 4.24 and VS 2019. You can try including``` #include "Styling/SlateTypes.h"```

**Comment by glenwrhodes** [comment]
Ahh, this is 4.23.  Looks like FInvalidatableBrushAttribute was added in 4.24.  I've commented out that line and it builds now, but of course the SWebCameraImage has no image. Do you know what the pre-4.24 code would be to set the Image without using FInvalidatableBrushAttribute ?

**Comment by bakjos** [comment]
@glenwrhodes I think you can assign directly the brush to the image then `Image = &Brush; `
